source 'https://rubygems.org'

gem 'watir'
gem 'page-object'
gem 'rspec'
gem 'httparty'
gem 'cucumber'
gem 'require_all'
gem 'rest-client'
gem 'uuid'
gem 'rake'
gem 'bunny'
gem 'activerecord-oracle_enhanced-adapter'
gem 'nokogiri'
